### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fuzzyfazzy** [vectorobject/faceswap#3]
I couldn't get this to work. Shame its not just a simple UI rather than using servers etc.

**Comment by vectorobject** [comment]
Could you please provide a detailed description of the issue you encountered,or any suggestions for improvements?

**Comment by vectorobject** [comment]
Did you open `runServer.bat` and then open `http://127.0.0.1:53499/` in your browser?
Don't manually open `runServer.bat`, and don't open the browser.
Just run `faceswap.exe` after you've got everything set up, and when you start it, it'll automatically open `runServer.bat` for you.
