### ISSUE TITLE
Getting Error While Starting

### ISSUE THREAD

**Issue by RFedz007** [vectorobject/faceswap#7]
Hi,

Hope you are doing Good :)

I am getting this below mentioned error while starting up...

(D:\Roop\faceswap\E\ff>chcp 65001 1>nul

D:\Roop\faceswap\E\ff>call C:\ProgramData\miniconda3\Scripts\activate.bat C:\ProgramData\miniconda3
The system cannot find the path specified.

D:\Roop\faceswap\E\ff>call conda activate roop
'conda' is not recognized as an internal or external command,
operable program or batch file.

D:\Roop\faceswap\E\ff>pushd G:\github\roop\roop_github\
The system cannot find the drive specified.

D:\Roop\faceswap\E\ff>python -u server.py 51520
python: can't open file 'D:\\Roop\\faceswap\\E\\ff\\server.py': [Errno 2] No such file or directory)

D:\Roop\faceswap\E\ff>pause
Press any key to continue . . .

Pls Assist how to fix this.

Thank You

**Comment by vectorobject** [comment]
Before running the program, you need to modify the `runServer.bat` file according to your environment in order to use your roop Python environment to run `server.py`.

First, assuming your roop directory is `G:\roop\`.

Below are several scenarios:

1. If you are using a virtual environment to run roop:
   - Using conda with installation path `D:\anaconda3` and environment name `abc`:
     ```batch
     chcp 65001>nul
     D:\anaconda3\Scripts\activate.bat D:\anaconda3
     call conda activate abc
     pushd G:\roop\
     python -u server.py %1
     pause
     ```
   - Using venv or virtualenv with the environment path `G:\roop\myenv` (not tested):
     ```batch
     chcp 65001>nul
     call G:\roop\myenv\Scripts\activate.bat
     pushd G:\roop\
     python -u server.py %1
     pause
     ```

2. If you are not using a virtual environment:
   ```batch
   chcp 65001>nul
   pushd G:\roop\
   python -u server.py %1
   pause
   ```

> Hi,
> 
> Hope you are doing Good :)
> 
> I am getting this below mentioned error while starting up...
> 
> (D:\Roop\faceswap\E\ff>chcp 65001 1>nul
> 
> D:\Roop\faceswap\E\ff>call C:\ProgramData\miniconda3\Scripts\activate.bat C:\ProgramData\miniconda3 The system cannot find the path specified.
> 
> D:\Roop\faceswap\E\ff>call conda activate roop 'conda' is not recognized as an internal or external command, operable program or batch file.
> 
> D:\Roop\faceswap\E\ff>pushd G:\github\roop\roop_github The system cannot find the drive specified.
> 
> D:\Roop\faceswap\E\ff>python -u server.py 51520 python: can't open file 'D:\Roop\faceswap\E\ff\server.py': [Errno 2] No such file or directory)
> 
> D:\Roop\faceswap\E\ff>pause Press any key to continue . . .
> 
> Pls Assist how to fix this.
> 
> Thank You

**Comment by RFedz007** [comment]
Thank You.

I have a small request. Is it possible to make a small tutorial on how to install & use from scratch via YouTube or any other link according to you, as It will be very helpful not for me, but for others also.

Thank You

**Comment by vectorobject** [comment]
> 谢谢。
> 
> 我有一个小要求。是否可以根据您的要求，通过YouTube或任何其他链接制作一个关于如何从头开始安装和使用的小教程，因为这不仅对我非常有帮助，而且对其他人也有帮助。
> 
> 谢谢

I will release a new version with added features in the future. I'll also consider simplifying the configuration in the new version. My free time is somewhat limited, so the next version might take a bit of time to arrive.

**Comment by vectorobject** [comment]
> 谢谢。
> 
> 我有一个小要求。是否可以根据您的要求，通过YouTube或任何其他链接制作一个关于如何从头开始安装和使用的小教程，因为这不仅对我非常有帮助，而且对其他人也有帮助。
> 
> 谢谢

If you encounter any other issues, feel free to raise them here.

**Comment by RFedz007** [comment]
I will explain you in detail exactly how I installed this.

I was already having Roop 1.3.2 in D path

I did

D/Roop

Pls check the attachment...

![1](https://github.com/vectorobject/faceswap/assets/50504604/8a0fd516-0c95-4bf1-a5e7-6528209cd1be)
![2](https://github.com/vectorobject/faceswap/assets/50504604/0e88c423-bb26-4321-83d4-b7434352dedb)

Thank You

**Comment by vectorobject** [comment]
Replace the content of `runServer.bat` with the following, then try running `faceswap.exe`:

```batch
chcp 65001>nul
pushd D:\Roop\roop\
python -u server.py %1
pause
```

**Comment by RFedz007** [comment]
Thanks a lot. I will try it now & let you know.

**Comment by RFedz007** [comment]
It's working now properly without any error. Thank You
